travis:
  secure:
    BINSTAR_TOKEN: mcsjtQaVcL+VC5IXN/b9jbD0hnaz/X8QFKMPJhLFaCDhyZRPNtE3B5Fe4MWc8MHdqpTLLxtQqpmRf6il3k5afhvCxZIU+OX9GlzdqJUmujsV1/cTihvW6SzppOpMIVTkx2q1tTUSfjk1ynR12G236uAvBBNTNvLEEuuxT0ZAMAkWRalO0C7laxGJTX8nEk2wrmmQLl7eW9LqNnVsqZAWyZ1xr9xugWt1gs5eOKp+JtPcpAQUo8G35iAKWThwyVQ4bLKIUfI+lq7aRPMWZu5T3f/PbW8tI34TknHzsnt8NfcpXUEdeOqs0EEJQ3Z62Z1G8q5rKLZQYxrhVfbCCuC6rNC+m6ZTmzdkeKa6vO2dZLE2vnkkoNLWZcrUQuTBJIW1NMQ3PLECzTyXRa9QjW6+hl6QH7WtQJoq5J/S2wJjYV/jRO4nqi2sDEWSH4Zar55ogYVCZXlP38quiri3yUN1kI18RTzkSNE8w/NqglLxct6WB4jupjcuGQm9a5KJvAPhlv1NwAaB1s8AzjBsvLzUVDGvNZ9uaxyMmQSjSRzz4bZE66ZjI7QDzupmuMlGTOcuWQBu1JhrhGwzioYb3lLyb9UnpzB64Rgf28RPfsSRbSeCAjFGZTEAAS39L4n6/TkPwt2CzPkUqo2jtMOsrUJGJkNxxQ6Lg3GgojWh4o3KG+8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
