travis:
  secure:
    BINSTAR_TOKEN: jdHeTRb36mqeUQu5YfnpXfPtnlq/+0okqabw/Ddpmi+G7wfnl3Zm43Aw+/Wod2gEcBa8V00KdzNt8jLE9JYiKF3WryI3GbwXGo7EM7p6SqSuNds32JfnQ3t67iLkEjrMdJBTwn+z+UMonP99PMw8Fx7C0JLcRmOM7UXzHvm/PC+kscGF1AOv36sse/APRAXRGfp/THH8QCa+0pJgHh/biAr3e4zSzIkzpuIWev1WohhxVZzOI14EK9q3XHCRlMZcuoTYnq6cbV1UztkhRdZV+yeGzWw4tkYdRFdGA10SMZZmxYIXoRhRZZfvjs4TpKV7TpioFkfqmWf1/TqCkVX/EAF4iSOJYeqNqgNiHnXZ5G8+7lzTJhSyPtylhl5b3BBTg83VQN6V19IrYA6vROHLqOS+xe8Zm82ahurbU1/SB12HCkzeoia6d8rc40e2zeV589i7e8mzXynIWpjdnKfk1ImVljrsdGrtcPFIg8q3Te+HNAurXqLWIL4k3Op1UYQC8jdZBSrwBdAg1A24HPdFlc+fOrF36jA38hz77Fl7veY9nuKXb1E2KQeugcFaODQ5RNOQ4dcmWuoURaA2xHgOWfkqc8TEyjLVmVJ4cYcusXROMF8mfyixNmwYxgN5rvEHhTQ47Ch7ulHQAeTVvo+naoJvuL+2vsNmwB+s/pqCxKs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
